### ISSUE TITLE
Excel slicers support?

### ISSUE THREAD

**Issue by merati** [felipe-prenholato/openpyxl#17]
Hi,
I have an Excel file which is a PivotTable. The problem is when I open xlts file and add data and save it as a new xlsx file, the library is removing all the slicers from the file. Is there any way to fix this issue and have the sliders?

**Comment by cah-steveanderson** [comment]
I actually have the same exact problem. This would be appreciated!

**Comment by shincy25** [comment]
Same problem for me, recently i'm doing a job to automate the slicer graph reports.
But whenever I updated the data and save it, the slicer will always missing.
Hope openpyxl to do something, would really appreciated.

**Comment by hyper-mage** [comment]
This problem still persists. I have pivots, graphs, and slicers already set up on a whole different sheet. Doesn't get touched but I guess the whole workbook has to pass through the OOXML or something and can't read the slicer lists. Is it possible to just not delete the slicer lists since it doesn't get touched?

My next best bet for automating this part is to keep the pivots, graphs, and slicers on a whole different sheet and save a templated output .xlsx which gets referenced by the reporting .xlsx. Heres to hoping that works, and if not then hopefully this gets fixed. I really like openpyxl for its ease of use.

**Comment by faheempython** [comment]
i have similar problem. I have an excel sheet with some pivot tables, slicers and pivotcharts and I just want to update the input data on another sheet but openpyxl is screwing up my charts as well. it seems its not able to process these charts correctly :( anyone knows of any workaround?

**Comment by arlethitgo** [comment]
The excel slicers are still automatically removed when I update the input data on a different worksheet. I hope there will be a support for this. Thanks.

**Comment by Valkrysa** [comment]
I would really appreciate a way to keep my slicers. Is there way to have openpyxl only edit the sheet that I select? That way the sheet with the slicers is preserved?
