### ISSUE TITLE
Apache can't start up when I using openpyxl in Django

### ISSUE THREAD

**Issue by c-rei** [felipe-prenholato/openpyxl#65]
When I deploy Django with mod_wsgi to Apache, Apache can not start up.
I just form openpyxl import load_workbook, while I comment them, Apache can start up.

My environment like below, Thanks any advises.

openpyxl 3.0.3
Django 3.1.2
Python 3.6.10
Apache 2.4

**Comment by SeilaPr** [comment]
Did you manage to solve it? 

Edit: I did manage to solve it. It turns out Apache must be checking the class imports or something and the import on openpyxl just makes it freeze. Solved it by putting the 'import openpyxl' inside the function instead of at the top of the .py,, this way Apache does not check it and it runs okay.
